absdir: /storage/singlecell/alice/local/micromamba/envs/sccafh5ad8/lib/python3.10/site-packages/scrnah5adscvi2leidenbyreswkfl
outdir: /storage/chentemp/alice/TM_project/clustering
infile:
- /storage/chentemp/alice/TM_project/scrnah5adfiles2scviwkfl/TM_culture.h5ad
bname:
- TM_culture
condaenv: null
nowtimestr: 230906231246
scrnah5adscvi2leidensbyresolution:
  condaenv: null
  label:
  - resolution_1
  resolution_1:
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1.0
  seed: 12345
